version: '3.9'
services:
  smtp:
    image: gessnerfl/fake-smtp-server
    ports:
      - "8081:8080"
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  elasticsearch:
    image: opensearchproject/opensearch:1.3.14
    hostname: elasticsearch
    restart: always
    healthcheck:
      test: curl -f http://elasticsearch:9200/
      interval: 2m
      timeout: 30s
      retries: 10
      start_period: 1m
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=opensearch
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    volumes:
      - "es_data:/usr/share/opensearch/data"
  nuxeo:
    image: nuxeo-composable-prompts:2023.1.0-SNAPSHOT
    env_file:
      - ./.env
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787
      - NUXEO_DEV=true
      - NUXEO_PACKAGES=${NUXEO_PACKAGES}
      - NUXEO_CLID=${CLID}
    hostname: nuxeo
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./conf.d:/etc/nuxeo/conf.d
volumes:
  es_data:
  mongodb_data:

